### ISSUE TITLE
[BUG] Missing refmap

### ISSUE THREAD

**Issue by Xyphenore** [Cathienna/CreateHaven#1]
**Describe the bug**

The refmap is missing, and a warning is printed on the console.

The warning from the console:

'Reference map 'CreateHaven.refmap.json' for create_haven.mixins.json could not be read. If this is a development environment you can ignore this message'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed to console.

**Additional context**
- Mod version: 0.0.3 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by Cathienna** [comment]
This can be safely ignored.
