### ISSUE TITLE
[BUG] Error in the recipe diamond_grit_sandpaper

### ISSUE THREAD

**Issue by Xyphenore** [Cathienna/CreateHaven#2]
**Describe the bug**

Unknown item 'createaddition:diamond_grit_sandpaper' for the recipe 'createhaven:crafting/diamond_grit_sandpaper'.

The error from the console:

'Parsing error loading recipe createhaven:crafting/diamond_grit_sandpaper
com.google.gson.JsonSyntaxException: Unknown item 'createaddition:diamond_grit_sandpaper''

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world.
- Error is printed to console.

**Additional context**
- Mod version: 0.0.3 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by Cathienna** [comment]
If you do not have the mod "Create Crafts & Additions" installed you can safely ignore it.

If you do have it installed, does the recipe work?

**Comment by Xyphenore** [comment]
The mod is installed. The diamond grit sandpaper is not visible in the creative inventory, JEI don't shows it and I can't give me the item. I just see Sand paper of Create.

But the game works.

**Comment by Cathienna** [comment]
I am not able to reproduce this.

Fresh install of this:
https://dl.dropboxusercontent.com/scl/fi/mi3hgb6cui8bkt5kufg43/CurseForge_tJXgMeQj37.png?rlkey=33sn13dm0lo4jgkb38tqodqut&dl=0

Shows up ingame with no errors:
https://dl.dropboxusercontent.com/scl/fi/mvwa9u869dva26jdud6cf/javaw_eA6mKKQrvf.png?rlkey=fjmkohtrx5hj37s669t78tpb0&dl=0

**Comment by Xyphenore** [comment]
My bad, I misread your previous message, to asking if "Create Crafts & Additions" is installed.

The mod "Create Crafts & Additions" is not installed. So I can ignore the error.

**Comment by Xyphenore** [comment]
The error is solved if the mod "Create Crafts & Additions" is installed.

Sorry for misread.

Maybe print an information to indicate that the recipe is not loaded, instead of printing the error.

**Comment by Cathienna** [comment]
The mod is not needed and the error can be safely ignored, it's just adding compatibility for that mod.
